import type { Metadata } from "next";
import "./global.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className="hydrated" suppressHydrationWarning>
      <body className={`bg-gray-100`}>{children}</body>
    </html>
  );
}
