name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build

      - name: Debug build
        run: |
          echo "현재 디렉토리: $(pwd)"
          echo "루트 내용:"
          ls -alh
          echo "out 폴더 내용:"
          ls -alh ./out || echo "❌ ./out 폴더 없음"

      - name: Deploy to Surge
        run: npx surge ./out ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }} --force
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
